FPS_STREAMS={}

MAX_TIME_STAMP_LEN = 32

PGIE_CLASS_NAME_CAR = "car"
SGIE_CLASS_NAME_LPD = "lpd"

CLASS_MAPPING = {
    PGIE_CLASS_NAME_CAR: 0, 
    SGIE_CLASS_NAME_LPD: 1
    }
REVERSE_CLASS_MAPPING = {
    0 : PGIE_CLASS_NAME_CAR,
    1 : SGIE_CLASS_NAME_LPD
}