FPS_STREAMS={}

MAX_TIME_STAMP_LEN = 32

PGIE_CLASS_ID_VEHICLE = 0
PGIE_CLASS_ID_BICYCLE = 1
PGIE_CLASS_ID_PERSON = 2
PGIE_CLASS_ID_ROADSIGN = 3

pgie_classes_str = ["Vehicle", "TwoWheeler", "Person", "Roadsign"]
