FPS_STREAMS={}

PGIE_CLASS_NAME_CAR = "car"
SGIE_CLASS_NAME_LPD = "lpd"

SAVED_COUNT = {}
FRAME_COUNT = {}

CLASS_MAPPING = {
    PGIE_CLASS_NAME_CAR:"0", 
    SGIE_CLASS_NAME_LPD:"1"
    }
REVERSE_CLASS_MAPPING = {
    0 : PGIE_CLASS_NAME_CAR,
    1 : SGIE_CLASS_NAME_LPD
}
